// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhDl2zNBVtQpH5eA0_Taetp1C9r7lPNJU',
    appId: '1:1011825797386:web:a8f5514c8e806de837f2f3',
    messagingSenderId: '1011825797386',
    projectId: 'journey-1318f',
    authDomain: 'journey-1318f.firebaseapp.com',
    storageBucket: 'journey-1318f.appspot.com',
    measurementId: 'G-HRMHX55KTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhDl2zNBVtQpH5eA0_Taetp1C9r7lPNJU',
    appId: '1:1011825797386:android:d64233bbd56ce05937f2f3',
    messagingSenderId: '1011825797386',
    projectId: 'journey-1318f',
    storageBucket: 'journey-1318f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhDl2zNBVtQpH5eA0_Taetp1C9r7lPNJU',
    appId: '1:1011825797386:ios:7dbaec723acba13237f2f3',
    messagingSenderId: '1011825797386',
    projectId: 'journey-1318f',
    storageBucket: 'journey-1318f.appspot.com',
    iosBundleId: 'com.example.sdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhDl2zNBVtQpH5eA0_Taetp1C9r7lPNJU',
    appId: '1:1011825797386:ios:4ffaa68f6e6bc1f637f2f3',
    messagingSenderId: '1011825797386',
    projectId: 'journey-1318f',
    storageBucket: 'journey-1318f.appspot.com',
    iosBundleId: 'com.example.sdd.RunnerTests',
  );
}
