name: Journey
description: A learning journey.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  flutter_pdfview: ^1.0.0 #pdf view
  syncfusion_flutter_pdfviewer: ^24.1.47
  advance_pdf_viewer: ^2.0.1
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter

  flutter_local_notifications: ^9.5.3+1
  cloud_firestore:  4.14.0   # Update to a version compatible with firebase_core

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: 4.16.0 

  provider: ^6.1.1
  http: ^1.0.0  
  googleapis: '11.4.0' 
  url_launcher: ^6.0.6 
  youtube_player_flutter: ^8.0.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  pdf: ^3.10.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "images/logo.png"
  android: true 
  ios: true
flutter:


  uses-material-design: true


  assets:
    - images/
    - images/datdatdtdat.png
    - images/javajvajva.png
    - images/ossoso.jpg
    - images/swee.png

    - images/Winnersi.png
    - images/Winners-pana.png
    - images/Winners-amico.png
    - images/Winners-cuate.png
    - assets/Tutorials.pdf
    - assets/Tutorials2.pdf
    

