name: Journey
description: A learning journey.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^9.5.3+1
  cloud_firestore: ^4.14.0  # Update to a version compatible with firebase_core

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3

  provider: ^6.1.1
  http: 1.1.0 
  googleapis: '11.4.0' 
  url_launcher: ^6.0.6 
  youtube_player_flutter: ^8.0.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 30 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/logo.png"
    icon_size: 120 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/logo.png"

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - images/
    - images\datdatdtdat.png
    - images/javajvajva.png
    - images/ossoso.jpg
    - images/swee.png
